---
version: '3'
services:

# START SERVICE dotnetcore_runtime31.base
  dotnetcore_runtime31:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.dotnetcore_runtime31.base:3.1.3
    environment: [${DOTNETCORE_RT31_ENVIRONMENT}]
    command: [${DOTNETCORE_RT31_COMMAND}]
    volumes: ['package_dotnetcore_rt31_dotnetcore_RUNTIME31_volume:/app']
    ports: []
    networks: [package_overlay]
    deploy:
      mode: ${DOTNETCORE_RT31_DEPLOY_MODE}
      replicas: ${DOTNETCORE_RT31_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${DOTNETCORE_RT31_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${DOTNETCORE_RT31_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${DOTNETCORE_RT31_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${DOTNETCORE_RT31_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${DOTNETCORE_RT31_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${DOTNETCORE_RT31_DEPLOY_LABELS}]
    labels: [${DOTNETCORE_RT31_LABELS}]
# END SERVICE dotnetcore_runtime31.base

volumes: {package_dotnetcore_rt31_dotnetcore_RUNTIME31_volume: { external: true }}
networks: {package_overlay: { external: true }}
