#!/usr/bin/env bash


prefix="package_dotnetcore_rt31_$2"

if [[ "package_dotnetcore_rt31_dotnetcore_rt31_dotnetcore_runtime31_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_dotnetcore_rt31_dotnetcore_rt31_dotnetcore_runtime31_volume
	fi
	
if [[ "package_dotnetcore_rt31_dotnetcore_rt31_dotnetcore_runtime31_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_dotnetcore_rt31_dotnetcore_rt31_dotnetcore_runtime31_volume:/app ${CONTECO_REGISTRY}$1 --interactive tar -C / -xvf /modeco/volumes/dotnetcore_rt31_dotnetcore_runtime31_volume.tar
		fi
		
