#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_dotnetcore_rt31_dotnetcore_runtime22_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_dotnetcore_rt31_dotnetcore_runtime22_volume
	fi
	
if [[ "package_dotnetcore_rt31_dotnetcore_runtime31_volume" == "$prefix"* ]] ; then
			executionplane --silent docker run -v package_dotnetcore_rt31_dotnetcore_runtime31_volume:/app ${CONTECO_REGISTRY}$1 --interactive cp -r /modeco/volumes/package_dotnetcore_rt31_dotnetcore_runtime31_volume/* /app
		fi
		
